import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import org.apache.lucene.queryparser.classic.ParseException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Makli
 */
public class ResultsDialog extends javax.swing.JDialog {

    /**
     * Creates new form ResultsDialog
     * @param parent
     * @param modal
     * @param TitleListModel
     * @param SumListModel
     */
    
    DefaultListModel<String> HelpModel = new DefaultListModel<>();
    DefaultListModel<String> HelpTermModel = new DefaultListModel<>();
    
    public ResultsDialog(java.awt.Frame parent, boolean modal, DefaultListModel<String> DocIDListModel, DefaultListModel<String> SumListModel, DefaultListModel<String> TermListModel) {
        super(parent, modal);
        initComponents();
        SetIcon();
        setLocationRelativeTo(null);
        TitlesList.setModel(DocIDListModel);
        
        // Copy the SumListModel argument to the global variable HelpModel
        for (int i = 0; i < SumListModel.size(); i++) {      // Copy the first
            HelpModel.addElement(SumListModel.elementAt(i));    // list to the second
        }
        
        // Copy the TermListModel argument to the global variable HelpTermModel
        for (int i = 0; i < TermListModel.size(); i++) {
            HelpTermModel.addElement(TermListModel.elementAt(i));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResultsPanel = new javax.swing.JPanel();
        OKBtn = new javax.swing.JButton();
        TitlesScrollPane = new javax.swing.JScrollPane();
        TitlesList = new javax.swing.JList();
        TitlesLbl = new javax.swing.JLabel();
        SumsLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SumTxtPane = new javax.swing.JTextPane();
        QueryExpansionBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Results");

        ResultsPanel.setBackground(new java.awt.Color(204, 204, 255));

        OKBtn.setText("OK");
        OKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKBtnActionPerformed(evt);
            }
        });

        TitlesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        TitlesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                TitlesListValueChanged(evt);
            }
        });
        TitlesScrollPane.setViewportView(TitlesList);

        TitlesLbl.setText("Title");

        SumsLbl.setText("Summary");

        jScrollPane2.setViewportView(SumTxtPane);

        QueryExpansionBtn.setText("Expand Query");
        QueryExpansionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueryExpansionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ResultsPanelLayout = new javax.swing.GroupLayout(ResultsPanel);
        ResultsPanel.setLayout(ResultsPanelLayout);
        ResultsPanelLayout.setHorizontalGroup(
            ResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultsPanelLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(TitlesLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SumsLbl)
                .addGap(220, 220, 220))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultsPanelLayout.createSequentialGroup()
                .addGroup(ResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ResultsPanelLayout.createSequentialGroup()
                        .addContainerGap(471, Short.MAX_VALUE)
                        .addComponent(OKBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(432, 432, 432))
                    .addGroup(ResultsPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(TitlesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(QueryExpansionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ResultsPanelLayout.setVerticalGroup(
            ResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultsPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(ResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitlesLbl)
                    .addComponent(SumsLbl))
                .addGap(18, 18, 18)
                .addGroup(ResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(TitlesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addComponent(OKBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QueryExpansionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ResultsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ResultsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKBtnActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_OKBtnActionPerformed

    private void TitlesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_TitlesListValueChanged
        if (TitlesList.getSelectedValue() != null) {
            SumTxtPane.setText(HelpModel.elementAt(TitlesList.getSelectedIndex()));
        }
    }//GEN-LAST:event_TitlesListValueChanged

    private void QueryExpansionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueryExpansionBtnActionPerformed
        ExpansionFrame expQuery = null;
        try {
            expQuery = new ExpansionFrame((DefaultListModel<String>) TitlesList.getModel(), HelpModel, HelpTermModel);
        } catch (IOException | ParseException ex) {
            Logger.getLogger(ResultsDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        expQuery.setVisible(true);
        expQuery.setAlwaysOnTop(true);
        expQuery.setLocation(this.getX(), this.getY());
    }//GEN-LAST:event_QueryExpansionBtnActionPerformed

    private void SetIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("IRicon.png")));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DefaultListModel<String> DocIDListModel = null;
                DefaultListModel<String> SumListModel = null;
                DefaultListModel<String> TermListModel = null;

                ResultsDialog dialog = new ResultsDialog(new javax.swing.JFrame(), true, DocIDListModel, SumListModel, TermListModel);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKBtn;
    private javax.swing.JButton QueryExpansionBtn;
    private javax.swing.JPanel ResultsPanel;
    private javax.swing.JTextPane SumTxtPane;
    private javax.swing.JLabel SumsLbl;
    private javax.swing.JLabel TitlesLbl;
    private javax.swing.JList TitlesList;
    private javax.swing.JScrollPane TitlesScrollPane;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
